name: Rust CI

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main, next ]

jobs:
  build:
    name: Run tests and doctests on ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.57.0", stable, beta, nightly]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Cache Cargo Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: build
      run: cargo build -v
      env:
        FEATURES: ${{ matrix.features }}
    - name: test
      if: ${{ matrix.rust == 'nightly' }}
      run: >
        cargo test -v &&
        cargo doc -v
      env:
        FEATURES: ${{ matrix.features }}

  build_big_endian:
    name: Run tests on big endian architecture

    # github actions does not support big endian systems directly, but it does support QEMU.
    # so we install qemu, then build and run the tests in an emulated mips system.
    # note: you can also use this approach to test for big endian locally.
    runs-on: ubuntu-20.04

    # we are using the cross project for cross compilation to mips:
    # https://github.com/cross-rs/cross
    steps:
      - uses: actions/checkout@v2

      - name: Install or use cached cross-rs/cross
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cross

      - name: Cache Cargo Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Start Docker (required for cross-rs)
        run: sudo systemctl start docker

      - name: Cross-Compile project to mips-unknown-linux-gnu
        run: |
          cross build --target=mips-unknown-linux-gnu --verbose -v
        env:
          FEATURES: ${{ matrix.features }}

      # https://github.com/cross-rs/cross#supported-targets
      - name: Cross-Run Tests in mips-unknown-linux-gnu using Qemu
        run: |
          cross test --target mips-unknown-linux-gnu --verbose -v
        env:
          FEATURES: ${{ matrix.features }}

  clippy:
    runs-on: ubuntu-20.04
    steps:
    - name: install-dependencies
      run: sudo apt update && sudo apt install ninja-build meson nasm
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - uses: actions-rs/cargo@v1
      with:
        args: clippy --all-features -- -D warnings
      env:
        SYSTEM_DEPS_DAV1D_BUILD_INTERNAL: always

  build_fuzz_cargo-fuzz:
    name: "Fuzz targets (cargo-fuzz)"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: build
      run: |
        cargo install cargo-fuzz
        cargo fuzz build
    - name: fuzz
      run: |
        for target in $(cargo fuzz list); do
          cargo fuzz run "$target" -- -runs=0;
        done

  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt
    - name: Run rustfmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check

  cargo-deny:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1

  verify_msrv:
    name: Verify Minimum Supported Rust Version in Cargo.toml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install or use cached `cargo-msrv`
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-msrv

      - name: Verify Minimum Rust Version
        run: cargo-msrv verify
